STANDINGS_FORMATTING = {
  "color_scale_inverse_cols": [
      "wins",
      "win_pct",
      "total_pf",
      "differential",
      "avg_opponent_rank",
      "cumulative_pa_rank",
      "avg_pf",
      "avg_differential",
      "player_games",
      "avg_player_games",
  ],
  "bold_min_cols": [
      "losses",
      "avg_opponent_rank",
      "cumulative_pa_rank",
  ],
  "vertical_borders": [
    "rank",
    "games_missed_injury",
    "avg_games_missed_injury",
    'player_games',
    'avg_player_games',
  ],
  "resize_cols": {
    "team_name": 190,
    "team_id": 63,
    "rank": 60,
    "wins": 60,
    "losses": 71,
    "ties": 60,
    "win_pct": 60,
    "total_pf": 60,
    "total_pa": 60,
    "differential": 98,
    "avg_opponent_rank": 118,
    "cumulative_pa_rank": 98,
    "avg_pf": 60,
    "avg_pa": 60,
    "avg_differential": 80,
    "games_missed_injury": 80,
    "games_missed_ir": 80,
    "total_games_missed": 106,
    "lost_points_injury": 98,
    "lost_points_ir": 98,
    "total_lost_points": 88,
    "avg_games_missed_injury": 116,
    "avg_games_missed_ir": 100,
    "avg_total_games_missed": 87,
    "avg_lost_points_injury": 82,
    "avg_lost_points_ir": 82,
    "avg_total_lost_points": 87,
    "player_games": 75,
    "bench_games": 75,
    "ir_games": 87,
    "total_missed_games": 94,
    "bench_points_lost": 75,
    "ir_points_lost": 83,
    "total_points_lost": 70,
    "avg_player_games": 95,
    "avg_bench_games": 96,
    "avg_ir_games": 74,
    "avg_total_missed_games": 86,
    "avg_bench_points_lost": 101,
    "avg_ir_points_lost": 74,
    "avg_total_points_lost": 98,
  },
}

WEEKLY_FORMATTING = {
  "color_scale_full_col_cols": [
    "rank",
    "pf_rank",
    "pa_rank",
    "cumulative_pf_rank",
    "cumulative_pa_rank",
  ],
  "color_scale_inverse_cols": [
    "wins",
    "win_pct",
    "pf",
    "differential",
    "pa_rank",
    "cumulative_pf",
    "cumulative_differential",
    "cumulative_pa_rank",
    "player_games",
  ],
  "bold_max_cols": [
    "wins",
    "win_pct",
    "pf",
    "differential",
    "games_missed_injury",
    "games_missed_ir",
    "total_games_missed",
    "lost_points_injury",
    "lost_points_ir",
    "total_lost_points",
  ],
  "bold_min_cols": [
    "pa",
  ],
  "vertical_borders": [
    "rank", 
    "games_missed_injury", 
    "cumulative_games_missed_injury",
    "player_games", 
  ],
  "resize_cols": {
    "week": 64,
    "team_name": 160,
    "team_id": 63,
    "opponent_name": 160,
    "rank": 60,
    "wins": 60,
    "losses": 71,
    "win_pct": 60,
    "pf": 46,
    "pa": 47,
    "differential": 98,
    "pf_rank": 76,
    "pa_rank": 79,
    "cumulative_pf": 98,
    "cumulative_pa": 98,
    "cumulative_differential": 104,
    "cumulative_pf_rank": 98,
    "cumulative_pa_rank": 98,
    "games_missed_injury": 80,
    "games_missed_ir": 80,
    "total_games_missed": 106,
    "lost_points_injury": 98,
    "lost_points_ir": 98,
    "total_lost_points": 88,
    "cumulative_games_missed_injury": 108,
    "cumulative_games_missed_ir": 108,
    "cumulative_total_games_missed": 106,
    "cumulative_lost_points_injury": 104,
    "cumulative_lost_points_ir": 104,
    "cumulative_total_lost_points": 98,
    "player_games": 75,
    "bench_games": 75,
    "ir_games": 87,
    "total_missed_games": 94,
    "bench_points_lost": 75,
    "ir_points_lost": 83,
    "total_points_lost": 70,
  },
}
